### ISSUE TITLE
feat: Customizing gRPC client's options 

### ISSUE THREAD

**Issue by aneterial** [ydb-platform/ydb-php-sdk#136]
# Feature Request

**Describe the Feature Request**

it would be nice to be able to customize the gPRC client's options like this:
```php
$config = [
    // ...
    'opts' => [
        'grpc.max_receive_message_length' => 8*1024*1024,
        'grpc.default_compression_algorithm' => 2,
        'grpc.default_compression_level' => 2,
    ],
]
$ydb = new \YdbPlatform\Ydb\Ydb($config);
```

**Describe Preferred Solution**

Expand functionality of `\YdbPlatform\Ydb\Ydb`  by adding a new property (array)

**Comment by rekby** [comment]
Hello, thanks for the issue
