### ISSUE TITLE
incorrect type casting unit32, unit64

### ISSUE THREAD

**Issue by bashkarev** [ydb-platform/ydb-php-sdk#19]
https://github.com/yandex-cloud/ydb-php-sdk/blob/d36974c1f1f4c539fa6a10723bd36cc786f99f49/src/QueryResult.php#L208-L211

unit32 > PHP_INT_MAX in 32 bit systems.
unit64 > PHP_INT_MAX in 64 bit systems.

**Comment by uh-zuh** [comment]
I think there are a lot of other problems on 32 bit systems hence it's enought to fix only UNIT64.
