### ISSUE TITLE
bug: YDB_400100 BAD_SESSION

### ISSUE THREAD

**Issue by gfh31fgh2** [ydb-platform/ydb-php-sdk#89]
# Bug Report

**YDB PHP SDK version:**
1.7.0
1.5.6 - здесь нет таких проблем

**Environment**
ubuntu18
JWT

**Current behavior:**

```
YDB Table BeginTransaction (YDB_400100 BAD_SESSION): Session not found: ydb://session/3?node_id=11111&id=xxxxxxxxI=

```

**Expected behavior:**

php working more than 12 hours

**Steps to reproduce:**

php working more than 12 hours

**Related code:**

https://github.com/gfh31fgh2/ydb-php-simple-driver

**Comment by gfh31fgh2** [comment]
пять и больше ретраев никак не меняют ситуацию

**Comment by ilyakharev** [comment]
В старых версих ретраи работали с ошибками, поэтому мы их поправили и их нужно вызывать явно.
Для использования кода с транзакцией используйте:
```php
$ydb->table()->retryTransaction(function(Session $session){
//Тут ваш код
}, $idempotent);
```
Где `$idempotent` признак идемпотентности транзакции (по умолчанию - false).
Также рекомендуется сделать транзакции имдепотентными, тогда ретраер будет работать лучше

Рекомендуем использовать версию v1.8.0

**Comment by gfh31fgh2** [comment]
обновились на 1.8.0 - получаем те же ошибки

**Comment by gfh31fgh2** [comment]
Все еще остаются ошибки

**Comment by ilyakharev** [comment]
Делать prepare и вызывать execute в prepare statement необходимо на одной сессии, то есть внутри одного ретраера.
Пример использования:
```php
$result = $table->retrySession(function (Session $session) {
    $prepare = $session->prepare($yql);
    return $prepare->execute($data);
});
```

**Comment by gfh31fgh2** [comment]
1.8.1 
с тем кодом что вы указали - ошибка осталась

**Comment by gfh31fgh2** [comment]
Косяк в команде 
`$output  = $rsa->sign($input);`

который иногда выполянется около 1 минуты

( https://github.com/ydb-platform/ydb-php-sdk/blob/72d39a41dc7441b5e6c637985bd9cab2ad2a50b1/src/Jwt/Jwt.php#L115 - при заходе в ELSE)

**Comment by rekby** [comment]
Исходная проблема решилась.

Сейчас осталась проблема со скоростью подписи токена, это будет делаться соседней задачей: https://github.com/ydb-platform/ydb-php-sdk/issues/102

Чтобы сохранять понятность истории.

**Comment by gfh31fgh2** [comment]
да, ретрай решает отчасти эту проблему
